336340 accreditation phase 1 waste licences and permits page2
DEFRA/epr-prn-accreditation-front-end pull request #30
Opened 2024-03-20 14:31 UTC by AtosSK

2024-03-20 15:18 UTC, atos-ajoyce commented on src/EPR.Accreditation.Portal/EPR.Accreditation.App/Services/AccreditationService.cs
> +        public WasteLicensesAndPermitsViewModel GetWasteLicensesAndPermitsViewModel(Guid id)
These methods should be async, for example public async Task<WasteLicensesAndPermitsViewModel>(Guid id) and then called with the await keyword

2024-03-20 15:48 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.App/Services/AccreditationService.cs
> +        public WasteLicensesAndPermitsViewModel GetWasteLicensesAndPermitsViewModel(Guid id)
Done.

2024-03-26 13:23 UTC, NikPeters-Atos requested changes

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [ActionName("WasteLicensesAndPermits")]
Put the action name in the HttpGet attribute

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [ActionName("WasteLicensesAndPermits")]
Same as above

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasAddress.cs
> +}
Why is this here? You don't need this

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasAgent.cs
> +}
Why is this here? You don't need this

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasReprocessingSite.cs
> +}
Why is this here? You don't need this

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/Site.cs
> +}
Same

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/SiteAuthority.cs
> +}
Same

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/RESTservices/HttpAccreditationService.cs
> +            await Post($"{id}", accreditation);
You're not creating an Accreditation - you're creating/update a waste permit.

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/RESTservices/Interfaces/IHttpAccreditationService.cs
> +        Task CreateAccreditation(
Don't need this

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            }
Don't manually copy properties over, use AutoMapper

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            wastePermit.PartBActivityReferenceNumber = wasteLicensesAndPermitsViewModel.ActivityNumber;
Use AutoMapper

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/Interfaces/IAccreditationService.cs
> +        WasteLicensesAndPermitsViewModel GetWasteLicensesAndPermitsViewModel(Guid id);
GetWastePermitViewModel - a better name

2024-03-26 13:23 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Views/Shared/WasteLicensesAndPermits.cshtml
> +                        Save and come back later
Hard coded english text. Use the partial view _SaveButtons instead. Everythings there you need

2024-03-26 13:29 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [ActionName("WasteLicensesAndPermits")]
Done.

2024-03-26 13:29 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [ActionName("WasteLicensesAndPermits")]
Done.

2024-03-26 13:32 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasAgent.cs
> +}
Required for Accreditation.Overseas Reporting object

2024-03-26 13:33 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasReprocessingSite.cs
> +}
Required for Accreditation.Overseas Reporting object

2024-03-26 13:34 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/RESTservices/Interfaces/IHttpAccreditationService.cs
> +        Task CreateAccreditation(
Removed.

2024-03-26 13:37 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/Interfaces/IAccreditationService.cs
> +        WasteLicensesAndPermitsViewModel GetWasteLicensesAndPermitsViewModel(Guid id);
Done.

2024-03-26 13:40 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Views/Shared/WasteLicensesAndPermits.cshtml
> +                        Save and come back later
Done.

2024-03-26 14:50 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            wastePermit.PartBActivityReferenceNumber = wasteLicensesAndPermitsViewModel.ActivityNumber;
Done.

2024-03-26 14:51 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            }
Done.

2024-03-27 10:32 UTC, NikPeters-Atos requested changes

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [HttpGet, ActionName("WasteLicensesAndPermits")]
The action name string should be part of the HttpGet: [HttpGet("WasteLicensesAndPermits")]

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [HttpPost, ActionName("WasteLicensesAndPermits")]
Same as above

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +            if (!ModelState.IsValid)
You need to ensure Save And Come Back later works. Have a look in BaseSiteController to understand how it works

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +            return View("CheckWastePermitExemption");
Should this not redirect to a new action, not return a different view?

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/Accreditation.cs
> +}
Why is this being added as a DTO? I don't believe you need it

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasAddress.cs
> +}
Why is this being added as a DTO? I don't believe you need it

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasAgent.cs
> +}
Why is this being added as a DTO? I don't believe you need it

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/OverseasReprocessingSite.cs
> +}
Why is this being added as a DTO? I don't believe you need it

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Enums/OperatorType.cs
> +}
Do you need this in your code? I don't think you do

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Profiles/AccreditationProfile.cs
> +                .ForMember(s => s.Id, opt => opt.Ignore());
I think we should remove the ID from WastePermit. It's not needed. I know this is just copied from Facade, but since we're here we may as well cover it.

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/RESTservices/HttpAccreditationService.cs
> +        public async Task CreateWastePermit(Guid id, DTOs.WastePermit wastePermit)
Can we put multiple parameters on seperate lines? It reads better

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +
Blank lines not need between member variables

2024-03-27 10:32 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            var wastePermit = _httpAccreditationService.GetWastePermit(id);
Add an await here and remove the Result property from line 33

2024-03-27 10:34 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [HttpGet, ActionName("WasteLicensesAndPermits")]
Done.

2024-03-27 10:35 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +        [HttpPost, ActionName("WasteLicensesAndPermits")]
Done.

2024-03-27 10:37 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +            return View("CheckWastePermitExemption");
Done.

2024-03-27 10:48 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Controllers/AccreditationController.cs
> +            if (!ModelState.IsValid)
Done.

2024-03-27 10:49 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/DTOs/Accreditation.cs
> +}
Used in accreditation.cs

2024-03-27 10:49 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Enums/OperatorType.cs
> +}
Used in accreditation..cs.

2024-03-27 10:50 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/RESTservices/HttpAccreditationService.cs
> +        public async Task CreateWastePermit(Guid id, DTOs.WastePermit wastePermit)
Done.

2024-03-27 10:51 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +
Done.

2024-03-27 11:03 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            var wastePermit = _httpAccreditationService.GetWastePermit(id);
Done.

2024-03-27 11:05 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Profiles/AccreditationProfile.cs
> +                .ForMember(s => s.Id, opt => opt.Ignore());
Done.

2024-04-04 08:36 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
>              var externalId = await _httpAccreditationService.CreateAccreditation(accreditation);
um..... why are you creating an accreditation in the constructor of a service?

2024-04-04 08:36 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +                wasteLicensesAndPermitsViewModel.Id = id;
Does the id need setting in the view model? I don't think it does

2024-04-04 08:36 UTC, NikPeters-Atos commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            WasteLicensesAndPermitsViewModel wasteLicensesAndPermitsViewModel = new WasteLicensesAndPermitsViewModel();
I think the mapper should be able to create the object even if the source is null. Better check that, because it will make cleaner code.

2024-04-04 08:45 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
>              var externalId = await _httpAccreditationService.CreateAccreditation(accreditation);
This is in the CreateAccreditation method

2024-04-04 08:52 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +            WasteLicensesAndPermitsViewModel wasteLicensesAndPermitsViewModel = new WasteLicensesAndPermitsViewModel();
Checked.
It will create a null object but I still need to assign the id. I will need the condition to assign the id value.

2024-04-04 08:57 UTC, AtosSK commented on src/EPR.Accreditation.Portal/EPR.Accreditation.Portal/Services/Accreditation/AccreditationService.cs
> +                wasteLicensesAndPermitsViewModel.Id = id;
That is the accreditationid, we need it to save the record.

2024-04-04 09:42 UTC, NikPeters-Atos approved these changes

2024-04-04 09:42 UTC, merged